### ISSUE TITLE
ESP32 generate seems to have broke. Cannot find core.a

### ISSUE THREAD

**Issue by ethancheez** [fprime-community/fprime-arduino#23]
Something with the `arduino-cli-cmake-wrapper` maybe?

```
$ fprime-util generate esp32
[INFO] Generating build directory at: /home/ethan/work/fprime-projects/fprime-community/fprime-tutorial-arduino-blinker/build-fprime-automatic-esp32
[INFO] Using toolchain file /home/ethan/work/fprime-projects/fprime-community/fprime-tutorial-arduino-blinker/fprime-arduino/cmake/toolchain/esp32.cmake for platform esp32
WARNING:arduino_cli_cmake_wrapper.parser:Unknown sections detected with titles: Creating esp32 image...,Creating esp32 image...
[ERROR] AssertionError occurred. Could not find core.a
Traceback (most recent call last):
  File "/home/ethan/venv/fprime/bin/arduino-cli-wrapper", line 8, in <module>
    sys.exit(main())
  File "/home/ethan/venv/fprime/lib/python3.10/site-packages/arduino_cli_cmake_wrapper/cli.py", line 241, in main
    output_data, cache_path = assemble_output_data(
  File "/home/ethan/venv/fprime/lib/python3.10/site-packages/arduino_cli_cmake_wrapper/cli.py", line 224, in assemble_output_data
    return data, sketch_cache(stages)
  File "/home/ethan/venv/fprime/lib/python3.10/site-packages/arduino_cli_cmake_wrapper/miner.py", line 140, in sketch_cache
    assert core_tokens, "Could not find core.a"
AssertionError: Could not find core.a
CMake Error at fprime-arduino/cmake/toolchain/support/arduino-wrapper.cmake:72 (message):
  Could not run 'arduino-cli' please install 'arduino-cli' and board
  'esp32:esp32:esp32'.
Call Stack (most recent call first):
  fprime-arduino/cmake/toolchain/support/arduino-support.cmake:43 (run_arduino_wrapper)
  fprime-arduino/cmake/toolchain/support/arduino-support.cmake:201 (set_arduino_build_settings)
  fprime-arduino/cmake/toolchain/esp32.cmake:22 (include)
  /usr/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:148 (include)
  CMakeLists.txt:5 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
[ERROR] CMake erred with return code 1. Partial build cache remains. Run purge to clean-up.
```

**Comment by ethancheez** [comment]
Version of the ESP32 toolchain got rid of `core.a`.

The latest version that works is:
```sh
arduino-cli core install esp32:esp32@2.0.9
```
